<?php

namespace Database\Seeders;

use App\Enums\AssetAvailabilityStatus;
use App\Enums\AssetCondition;
use App\Models\Asset;
use App\Models\AssetCategory;
use Illuminate\Database\Seeder;

class AssetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $laptopCat = AssetCategory::where('code', 'CAT-LPT')->first()?->id ?? 1;
        $smartphoneCat = AssetCategory::where('code', 'CAT-SMP')->first()?->id ?? 2;
        $kameraCat = AssetCategory::where('code', 'CAT-CAM')->first()?->id ?? 3;
        $audioVisualCat = AssetCategory::where('code', 'CAT-AV')->first()?->id ?? 4;
        $aksesorisCat = AssetCategory::where('code', 'CAT-ACC')->first()?->id ?? 5;

        $assets = [
            // ==========================================
            // --- 27 LAPTOPS (ID: 1 - 27) ---
            // ==========================================
            [
                'id' => 1,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-001',
                'name' => 'Laptop Acer Aspire 5 #1',
                'brand' => 'Acer',
                'model' => 'Aspire 5 A514',
                'serial_number' => 'SN-ACER-ASP5-001',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-2.jpg',
                'notes' => 'Core i5-1135G7, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 2,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-002',
                'name' => 'Laptop Acer Aspire 5 #2',
                'brand' => 'Acer',
                'model' => 'Aspire 5 A514',
                'serial_number' => 'SN-ACER-ASP5-002',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-3.jpg',
                'notes' => 'Core i5-1135G7, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 3,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-003',
                'name' => 'Laptop Asus Vivobook #3',
                'brand' => 'Asus',
                'model' => 'Vivobook 14 A1404',
                'serial_number' => 'SN-ASUS-VIVO-003',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-4.jpg',
                'notes' => 'Core i5-1235U, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 4,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-004',
                'name' => 'Laptop Asus Vivobook #4',
                'brand' => 'Asus',
                'model' => 'Vivobook 14 A1404',
                'serial_number' => 'SN-ASUS-VIVO-004',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-5.jpg',
                'notes' => 'Core i5-1235U, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 5,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-005',
                'name' => 'Laptop Asus Vivobook #5',
                'brand' => 'Asus',
                'model' => 'Vivobook 14 A1404',
                'serial_number' => 'SN-ASUS-VIVO-005',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-6.jpg',
                'notes' => 'Core i5-1235U, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 6,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-006',
                'name' => 'Laptop Asus Vivobook #6',
                'brand' => 'Asus',
                'model' => 'Vivobook 14 A1404',
                'serial_number' => 'SN-ASUS-VIVO-006',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-6.jpg',
                'notes' => 'Core i5-1235U, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 7,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-007',
                'name' => 'Laptop Lenovo ThinkPad L14 #7',
                'brand' => 'Lenovo',
                'model' => 'ThinkPad L14 Gen 2',
                'serial_number' => 'SN-LNV-TPAD-007',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-8.jpg',
                'notes' => 'Ryzen 5 PRO, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 8,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-008',
                'name' => 'Laptop Lenovo ThinkPad E14 #8',
                'brand' => 'Lenovo',
                'model' => 'ThinkPad E14 Gen 4',
                'serial_number' => 'SN-LNV-TPAD-008',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-10.jpg',
                'notes' => 'Core i5-1235U, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 9,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-009',
                'name' => 'Laptop HP Pavilion 14 #9',
                'brand' => 'HP',
                'model' => 'Pavilion 14-dv2000',
                'serial_number' => 'SN-HP-PAV-009',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-12.jpg',
                'notes' => 'Core i5-1235U, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 10,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-010',
                'name' => 'Laptop HP 240 G8 #10',
                'brand' => 'HP',
                'model' => 'HP 240 G8',
                'serial_number' => 'SN-HP-240-010',
                'condition' => AssetCondition::RusakRingan,
                'availability_status' => AssetAvailabilityStatus::Perbaikan,
                'photo_path' => 'items/laptop-13.jpg',
                'notes' => 'Core i3-1115G4, RAM 8GB, SSD 256GB. Dalam perbaikan keyboard.',
            ],
            [
                'id' => 11,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-011',
                'name' => 'Laptop Dell Latitude 3420 #11',
                'brand' => 'Dell',
                'model' => 'Latitude 3420',
                'serial_number' => 'SN-DELL-LAT-011',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-14.jpg',
                'notes' => 'Core i5-1135G7, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 12,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-012',
                'name' => 'Laptop Dell Inspiron 15 #12',
                'brand' => 'Dell',
                'model' => 'Inspiron 3511',
                'serial_number' => 'SN-DELL-INSP-012',
                'condition' => AssetCondition::RusakBerat,
                'availability_status' => AssetAvailabilityStatus::TidakTersedia,
                'photo_path' => 'items/laptop-16.jpg',
                'notes' => 'Layar bergaris, unit tidak dapat dipinjam.',
            ],
            [
                'id' => 13,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-013',
                'name' => 'Laptop Acer Swift 3 #13',
                'brand' => 'Acer',
                'model' => 'Swift 3 SF314',
                'serial_number' => 'SN-ACER-SW3-013',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-21.jpg',
                'notes' => 'Core i5-1135G7, RAM 8GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 14,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-014',
                'name' => 'Laptop Acer Swift 3 #14',
                'brand' => 'Acer',
                'model' => 'Swift 3 SF314',
                'serial_number' => 'SN-ACER-SW3-014',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-25.jpg',
                'notes' => 'Core i5-1135G7, RAM 8GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 15,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-015',
                'name' => 'Laptop Asus ExpertBook #15',
                'brand' => 'Asus',
                'model' => 'ExpertBook B1400',
                'serial_number' => 'SN-ASUS-EXP-015',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-27.jpg',
                'notes' => 'Core i5-1135G7, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 16,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-016',
                'name' => 'Laptop Asus ExpertBook #16',
                'brand' => 'Asus',
                'model' => 'ExpertBook B1400',
                'serial_number' => 'SN-ASUS-EXP-016',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-noname.jpg',
                'notes' => 'Core i5-1135G7, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 17,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-017',
                'name' => 'Laptop Lenovo IdeaPad 3 #17',
                'brand' => 'Lenovo',
                'model' => 'IdeaPad 3 14ITL6',
                'serial_number' => 'SN-LNV-IP3-017',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/lapotp-19.jpg',
                'notes' => 'Ryzen 5 5500U, RAM 8GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 18,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-018',
                'name' => 'Laptop Lenovo IdeaPad 3 #18',
                'brand' => 'Lenovo',
                'model' => 'IdeaPad 3 14ITL6',
                'serial_number' => 'SN-LNV-IP3-018',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-2.jpg',
                'notes' => 'Ryzen 5 5500U, RAM 8GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 19,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-019',
                'name' => 'Laptop HP ProBook 440 G8 #19',
                'brand' => 'HP',
                'model' => 'ProBook 440 G8',
                'serial_number' => 'SN-HP-PB440-019',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-3.jpg',
                'notes' => 'Core i5-1135G7, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 20,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-020',
                'name' => 'Laptop HP ProBook 440 G8 #20',
                'brand' => 'HP',
                'model' => 'ProBook 440 G8',
                'serial_number' => 'SN-HP-PB440-020',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-4.jpg',
                'notes' => 'Core i5-1135G7, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 21,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-021',
                'name' => 'Laptop Dell Vostro 3400 #21',
                'brand' => 'Dell',
                'model' => 'Vostro 3400',
                'serial_number' => 'SN-DELL-VOS-021',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-5.jpg',
                'notes' => 'Core i5-1135G7, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 22,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-022',
                'name' => 'Laptop Dell Vostro 3400 #22',
                'brand' => 'Dell',
                'model' => 'Vostro 3400',
                'serial_number' => 'SN-DELL-VOS-022',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-6.jpg',
                'notes' => 'Core i5-1135G7, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 23,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-023',
                'name' => 'Laptop Acer Aspire 3 #23',
                'brand' => 'Acer',
                'model' => 'Aspire 3 A314',
                'serial_number' => 'SN-ACER-ASP3-023',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-8.jpg',
                'notes' => 'Ryzen 3 7320U, RAM 8GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 24,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-024',
                'name' => 'Laptop Asus Zenbook 14 #24',
                'brand' => 'Asus',
                'model' => 'Zenbook UM425',
                'serial_number' => 'SN-ASUS-ZEN-024',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-10.jpg',
                'notes' => 'Ryzen 5 5500U, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 25,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-025',
                'name' => 'Laptop Lenovo V14 Gen 2 #25',
                'brand' => 'Lenovo',
                'model' => 'Lenovo V14-ITL',
                'serial_number' => 'SN-LNV-V14-025',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-12.jpg',
                'notes' => 'Core i5-1135G7, RAM 8GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 26,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-026',
                'name' => 'Laptop HP 14s #26',
                'brand' => 'HP',
                'model' => 'HP 14s-fq1000',
                'serial_number' => 'SN-HP-14S-026',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-14.jpg',
                'notes' => 'Ryzen 5 5500U, RAM 8GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],
            [
                'id' => 27,
                'asset_category_id' => $laptopCat,
                'asset_code' => 'AST-LPT-027',
                'name' => 'Laptop Dell Latitude 3520 #27',
                'brand' => 'Dell',
                'model' => 'Latitude 3520',
                'serial_number' => 'SN-DELL-LAT-027',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/laptop-16.jpg',
                'notes' => 'Core i5-1135G7, RAM 16GB, SSD 512GB. Lokasi: Ruang TEFA 1.',
            ],

            // ==========================================
            // --- SMARTPHONES (ID: 28 - 30) ---
            // ==========================================
            [
                'id' => 28,
                'asset_category_id' => $smartphoneCat,
                'asset_code' => 'AST-SMP-001',
                'name' => 'Samsung Galaxy A54 5G #1',
                'brand' => 'Samsung',
                'model' => 'Galaxy A54 5G',
                'serial_number' => 'SN-SMSG-A54-001',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/hp-21.jpg',
                'notes' => 'RAM 8GB, Storage 256GB. Testing unit mobile TEFA.',
            ],
            [
                'id' => 29,
                'asset_category_id' => $smartphoneCat,
                'asset_code' => 'AST-SMP-002',
                'name' => 'Xiaomi Redmi Note 12 #2',
                'brand' => 'Xiaomi',
                'model' => 'Redmi Note 12',
                'serial_number' => 'SN-XIAO-RN12-002',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/hp-25.jpg',
                'notes' => 'RAM 8GB, Storage 128GB. Testing unit mobile TEFA.',
            ],
            [
                'id' => 30,
                'asset_category_id' => $smartphoneCat,
                'asset_code' => 'AST-SMP-003',
                'name' => 'iPhone 11 64GB Testing Unit #3',
                'brand' => 'Apple',
                'model' => 'iPhone 11 64GB',
                'serial_number' => 'SN-APPL-IPH11-003',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => 'items/hp-30.jpg',
                'notes' => 'iOS testing unit untuk multimedia dan mobile dev.',
            ],

            // ==========================================
            // --- KAMERA & MULTIMEDIA (ID: 31 - 35) ---
            // ==========================================
            [
                'id' => 31,
                'asset_category_id' => $kameraCat,
                'asset_code' => 'AST-CAM-001',
                'name' => 'Kamera DSLR Canon EOS 3000D Kit',
                'brand' => 'Canon',
                'model' => 'EOS 3000D',
                'serial_number' => 'SN-CAN-3000D-001',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => null,
                'notes' => 'Lensa 18-55mm DC III, baterai, charger. Studio TEFA.',
            ],
            [
                'id' => 32,
                'asset_category_id' => $kameraCat,
                'asset_code' => 'AST-CAM-002',
                'name' => 'Kamera Mirrorless Sony Alpha A6400',
                'brand' => 'Sony',
                'model' => 'ILCE-6400',
                'serial_number' => 'SN-SNY-A6400-002',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => null,
                'notes' => 'Lensa 16-50mm OSS, baterai ekstra. Studio TEFA.',
            ],
            [
                'id' => 33,
                'asset_category_id' => $audioVisualCat,
                'asset_code' => 'AST-AV-001',
                'name' => 'Wireless Microphone Boya BY-V2 (Dual)',
                'brand' => 'Boya',
                'model' => 'BY-V2',
                'serial_number' => 'SN-BOYA-BYV2-001',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => null,
                'notes' => '2 Transmitter, 1 Receiver USB-C / Lightning.',
            ],
            [
                'id' => 34,
                'asset_category_id' => $audioVisualCat,
                'asset_code' => 'AST-AV-002',
                'name' => 'Proyektor Epson EB-E500 3300 Lumens',
                'brand' => 'Epson',
                'model' => 'EB-E500',
                'serial_number' => 'SN-EPS-EBE500-001',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => null,
                'notes' => '3300 Lumens XGA, kabel HDMI & remote.',
            ],
            [
                'id' => 35,
                'asset_category_id' => $aksesorisCat,
                'asset_code' => 'AST-ACC-001',
                'name' => 'Gimbal Stabilizer DJI Osmo Mobile 6',
                'brand' => 'DJI',
                'model' => 'Osmo Mobile 6',
                'serial_number' => 'SN-DJI-OM6-001',
                'condition' => AssetCondition::Baik,
                'availability_status' => AssetAvailabilityStatus::Tersedia,
                'photo_path' => null,
                'notes' => '3-Axis gimbal stabilizer dengan magnetic phone clamp.',
            ],
        ];

        foreach ($assets as $asset) {
            Asset::updateOrCreate(
                ['id' => $asset['id']],
                $asset
            );
        }
    }
}
