<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $laptop = Category::where('nama', 'Laptop')->first()?->id ?? 1;
        $smartphone = Category::where('nama', 'Smartphone')->first()?->id ?? 2;
        $kamera = Category::where('nama', 'Kamera')->first()?->id ?? 3;
        $audioVisual = Category::where('nama', 'Audio & Visual')->first()?->id ?? 4;
        $aksesoris = Category::where('nama', 'Aksesoris & Peralatan')->first()?->id ?? 5;

        $items = [
            // --- LAPTOP (1 - 12) ---
            [
                'id' => 1,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-ACER-001',
                'nama_barang' => 'Laptop Acer Aspire 5 #1',
                'merk' => 'Acer',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Tersedia',
                'gambar' => 'laptop-2.jpg',
            ],
            [
                'id' => 2,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-ACER-002',
                'nama_barang' => 'Laptop Acer Aspire 5 #2',
                'merk' => 'Acer',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Tersedia',
                'gambar' => 'laptop-3.jpg',
            ],
            [
                'id' => 3,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-ASUS-003',
                'nama_barang' => 'Laptop Asus Vivobook #3',
                'merk' => 'Asus',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Tersedia',
                'gambar' => 'laptop-4.jpg',
            ],
            [
                'id' => 4,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-ASUS-004',
                'nama_barang' => 'Laptop Asus Vivobook #4',
                'merk' => 'Asus',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Dipinjam',
                'gambar' => 'laptop-5.jpg',
            ],
            [
                'id' => 5,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-ASUS-005',
                'nama_barang' => 'Laptop Asus Vivobook #5',
                'merk' => 'Asus',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Tersedia',
                'gambar' => 'laptop-6.jpg',
            ],
            [
                'id' => 6,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-ASUS-006',
                'nama_barang' => 'Laptop Asus Vivobook #6',
                'merk' => 'Asus',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Tersedia',
                'gambar' => 'laptop-6.jpg',
            ],
            [
                'id' => 7,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-LNV-007',
                'nama_barang' => 'Laptop Lenovo ThinkPad L14 #7',
                'merk' => 'Lenovo',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Tersedia',
                'gambar' => 'laptop-8.jpg',
            ],
            [
                'id' => 8,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-LNV-008',
                'nama_barang' => 'Laptop Lenovo ThinkPad E14 #8',
                'merk' => 'Lenovo',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Dipinjam',
                'gambar' => 'laptop-10.jpg',
            ],
            [
                'id' => 9,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-HP-009',
                'nama_barang' => 'Laptop HP Pavilion 14 #9',
                'merk' => 'HP',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Tersedia',
                'gambar' => 'laptop-12.jpg',
            ],
            [
                'id' => 10,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-HP-010',
                'nama_barang' => 'Laptop HP 240 G8 #10',
                'merk' => 'HP',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Maintenance',
                'gambar' => 'laptop-13.jpg',
            ],
            [
                'id' => 11,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-DELL-011',
                'nama_barang' => 'Laptop Dell Latitude 3420 #11',
                'merk' => 'Dell',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Tersedia',
                'gambar' => 'laptop-14.jpg',
            ],
            [
                'id' => 12,
                'category_id' => $laptop,
                'kode_unik' => 'LPT-DELL-012',
                'nama_barang' => 'Laptop Dell Inspiron 15 #12',
                'merk' => 'Dell',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Rusak',
                'gambar' => 'laptop-16.jpg',
            ],

            // --- SMARTPHONE (13 - 20) ---
            [
                'id' => 13,
                'category_id' => $smartphone,
                'kode_unik' => 'SMP-SMSG-013',
                'nama_barang' => 'Samsung Galaxy A54 5G #13',
                'merk' => 'Samsung',
                'lokasi_ruangan' => 'Ruang TEFA 2',
                'status' => 'Tersedia',
                'gambar' => 'hp-21.jpg',
            ],
            [
                'id' => 14,
                'category_id' => $smartphone,
                'kode_unik' => 'SMP-SMSG-014',
                'nama_barang' => 'Samsung Galaxy A34 5G #14',
                'merk' => 'Samsung',
                'lokasi_ruangan' => 'Ruang TEFA 2',
                'status' => 'Dipinjam',
                'gambar' => 'hp-22.jpg',
            ],
            [
                'id' => 15,
                'category_id' => $smartphone,
                'kode_unik' => 'SMP-XIAO-015',
                'nama_barang' => 'Xiaomi Redmi Note 12 #15',
                'merk' => 'Xiaomi',
                'lokasi_ruangan' => 'Ruang TEFA 2',
                'status' => 'Tersedia',
                'gambar' => 'hp-25.jpg',
            ],
            [
                'id' => 16,
                'category_id' => $smartphone,
                'kode_unik' => 'SMP-XIAO-016',
                'nama_barang' => 'Xiaomi Poco M5 #16',
                'merk' => 'Xiaomi',
                'lokasi_ruangan' => 'Ruang TEFA 2',
                'status' => 'Tersedia',
                'gambar' => 'hp-30.jpg',
            ],
            [
                'id' => 17,
                'category_id' => $smartphone,
                'kode_unik' => 'SMP-RLM-017',
                'nama_barang' => 'Realme 10 Pro #17',
                'merk' => 'Realme',
                'lokasi_ruangan' => 'Ruang TEFA 2',
                'status' => 'Tersedia',
                'gambar' => 'hp-21.jpg',
            ],
            [
                'id' => 18,
                'category_id' => $smartphone,
                'kode_unik' => 'SMP-OPPO-018',
                'nama_barang' => 'Oppo Reno 8T #18',
                'merk' => 'Oppo',
                'lokasi_ruangan' => 'Ruang TEFA 2',
                'status' => 'Maintenance',
                'gambar' => 'hp-22.jpg',
            ],
            [
                'id' => 19,
                'category_id' => $smartphone,
                'kode_unik' => 'SMP-VIVO-019',
                'nama_barang' => 'Vivo Y36 5G #19',
                'merk' => 'Vivo',
                'lokasi_ruangan' => 'Ruang TEFA 2',
                'status' => 'Tersedia',
                'gambar' => 'hp-25.jpg',
            ],
            [
                'id' => 20,
                'category_id' => $smartphone,
                'kode_unik' => 'SMP-IPH-020',
                'nama_barang' => 'iPhone 11 64GB Testing Unit #20',
                'merk' => 'Apple',
                'lokasi_ruangan' => 'Ruang TEFA 2',
                'status' => 'Dipinjam',
                'gambar' => 'hp-30.jpg',
            ],

            // --- KAMERA & FOTOGRAFI (21 - 26) ---
            [
                'id' => 21,
                'category_id' => $kamera,
                'kode_unik' => 'CAM-CANON-021',
                'nama_barang' => 'Kamera DSLR Canon EOS 3000D Kit',
                'merk' => 'Canon',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 22,
                'category_id' => $kamera,
                'kode_unik' => 'CAM-CANON-022',
                'nama_barang' => 'Kamera DSLR Canon EOS 200D Mark II',
                'merk' => 'Canon',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 23,
                'category_id' => $kamera,
                'kode_unik' => 'CAM-SONY-023',
                'nama_barang' => 'Kamera Mirrorless Sony Alpha A6400',
                'merk' => 'Sony',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Dipinjam',
                'gambar' => null,
            ],
            [
                'id' => 24,
                'category_id' => $kamera,
                'kode_unik' => 'CAM-SONY-024',
                'nama_barang' => 'Kamera Mirrorless Sony ZV-E10',
                'merk' => 'Sony',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 25,
                'category_id' => $kamera,
                'kode_unik' => 'CAM-LENS-025',
                'nama_barang' => 'Lensa Canon EF 50mm f/1.8 STM',
                'merk' => 'Canon',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 26,
                'category_id' => $kamera,
                'kode_unik' => 'CAM-LENS-026',
                'nama_barang' => 'Lensa Sony E 35mm f/1.8 OSS',
                'merk' => 'Sony',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Maintenance',
                'gambar' => null,
            ],

            // --- AUDIO & VISUAL (27 - 32) ---
            [
                'id' => 27,
                'category_id' => $audioVisual,
                'kode_unik' => 'AUD-BOYA-027',
                'nama_barang' => 'Wireless Microphone Boya BY-V2 (Dual)',
                'merk' => 'Boya',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 28,
                'category_id' => $audioVisual,
                'kode_unik' => 'AUD-RODE-028',
                'nama_barang' => 'Microphone Shotgun Rode VideoMicro',
                'merk' => 'Rode',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 29,
                'category_id' => $audioVisual,
                'kode_unik' => 'PRJ-EPSON-029',
                'nama_barang' => 'Proyektor Epson EB-E500 3300 Lumens',
                'merk' => 'Epson',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 30,
                'category_id' => $audioVisual,
                'kode_unik' => 'PRJ-BENQ-030',
                'nama_barang' => 'Proyektor BenQ MX560 XGA',
                'merk' => 'BenQ',
                'lokasi_ruangan' => 'Ruang TEFA 2',
                'status' => 'Dipinjam',
                'gambar' => null,
            ],
            [
                'id' => 31,
                'category_id' => $audioVisual,
                'kode_unik' => 'AUD-SPK-031',
                'nama_barang' => 'Portable Wireless PA Speaker Behringer',
                'merk' => 'Behringer',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 32,
                'category_id' => $audioVisual,
                'kode_unik' => 'AUD-MIX-032',
                'nama_barang' => 'Audio Mixer Yamaha MG10XU 10-Channel',
                'merk' => 'Yamaha',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Tersedia',
                'gambar' => null,
            ],

            // --- AKSESORIS & PERALATAN (33 - 38) ---
            [
                'id' => 33,
                'category_id' => $aksesoris,
                'kode_unik' => 'ACC-TAKARA-033',
                'nama_barang' => 'Tripod Kamera Takara ECO-196A',
                'merk' => 'Takara',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 34,
                'category_id' => $aksesoris,
                'kode_unik' => 'ACC-DJI-034',
                'nama_barang' => 'Gimbal Stabilizer DJI Osmo Mobile 6',
                'merk' => 'DJI',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 35,
                'category_id' => $aksesoris,
                'kode_unik' => 'ACC-LIGHT-035',
                'nama_barang' => 'Ring Light Godox LR150 Bi-Color',
                'merk' => 'Godox',
                'lokasi_ruangan' => 'Studio TEFA',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 36,
                'category_id' => $aksesoris,
                'kode_unik' => 'ACC-TOOL-036',
                'nama_barang' => 'Toolkit Reparasi Komputer Jakemy 145-in-1',
                'merk' => 'Jakemy',
                'lokasi_ruangan' => 'Ruang TEFA 1',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 37,
                'category_id' => $aksesoris,
                'kode_unik' => 'ACC-LAN-037',
                'nama_barang' => 'Crimping Tool & Cable Tester Kit RJ45',
                'merk' => 'Schneider',
                'lokasi_ruangan' => 'Laboratorium Multimedia',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
            [
                'id' => 38,
                'category_id' => $aksesoris,
                'kode_unik' => 'ACC-SWT-038',
                'nama_barang' => 'Switch Gigabit TP-Link TL-SG1016D 16-Port',
                'merk' => 'TP-Link',
                'lokasi_ruangan' => 'Ruang Server TEFA',
                'status' => 'Tersedia',
                'gambar' => null,
            ],
        ];

        foreach ($items as $item) {
            Item::updateOrCreate(
                ['id' => $item['id']],
                $item
            );
        }
    }
}
